// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: activity_logger/v1/activity_logger.proto

package activity_logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,4,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_activity_logger_v1_activity_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LogRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *LogRequest) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_activity_logger_v1_activity_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_activity_logger_v1_activity_logger_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ActivityLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	EntityId      int64                  `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,5,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityLog) Reset() {
	*x = ActivityLog{}
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLog) ProtoMessage() {}

func (x *ActivityLog) ProtoReflect() protoreflect.Message {
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLog.ProtoReflect.Descriptor instead.
func (*ActivityLog) Descriptor() ([]byte, []int) {
	return file_activity_logger_v1_activity_logger_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivityLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActivityLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActivityLog) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ActivityLog) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

func (x *ActivityLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ActivityLog         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_logger_v1_activity_logger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_activity_logger_v1_activity_logger_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogsResponse) GetLogs() []*ActivityLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_activity_logger_v1_activity_logger_proto protoreflect.FileDescriptor

const file_activity_logger_v1_activity_logger_proto_rawDesc = "" +
	"\n" +
	"(activity_logger/v1/activity_logger.proto\x12\x12activity_logger.v1\"}\n" +
	"\n" +
	"LogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12!\n" +
	"\fdetails_json\x18\x04 \x01(\tR\vdetailsJson\"L\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"W\n" +
	"\x0eGetLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xac\x01\n" +
	"\vActivityLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\x03R\bentityId\x12!\n" +
	"\fdetails_json\x18\x05 \x01(\tR\vdetailsJson\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"F\n" +
	"\x0fGetLogsResponse\x123\n" +
	"\x04logs\x18\x01 \x03(\v2\x1f.activity_logger.v1.ActivityLogR\x04logs2\xb1\x01\n" +
	"\x0eActivityLogger\x12K\n" +
	"\bLogEvent\x12\x1e.activity_logger.v1.LogRequest\x1a\x1f.activity_logger.v1.LogResponse\x12R\n" +
	"\aGetLogs\x12\".activity_logger.v1.GetLogsRequest\x1a#.activity_logger.v1.GetLogsResponseBVZTgithub.com/kirill010106/todo-notificator/root/pkg/activity_logger/v1;activity_loggerb\x06proto3"

var (
	file_activity_logger_v1_activity_logger_proto_rawDescOnce sync.Once
	file_activity_logger_v1_activity_logger_proto_rawDescData []byte
)

func file_activity_logger_v1_activity_logger_proto_rawDescGZIP() []byte {
	file_activity_logger_v1_activity_logger_proto_rawDescOnce.Do(func() {
		file_activity_logger_v1_activity_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_logger_v1_activity_logger_proto_rawDesc), len(file_activity_logger_v1_activity_logger_proto_rawDesc)))
	})
	return file_activity_logger_v1_activity_logger_proto_rawDescData
}

var file_activity_logger_v1_activity_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_activity_logger_v1_activity_logger_proto_goTypes = []any{
	(*LogRequest)(nil),      // 0: activity_logger.v1.LogRequest
	(*LogResponse)(nil),     // 1: activity_logger.v1.LogResponse
	(*GetLogsRequest)(nil),  // 2: activity_logger.v1.GetLogsRequest
	(*ActivityLog)(nil),     // 3: activity_logger.v1.ActivityLog
	(*GetLogsResponse)(nil), // 4: activity_logger.v1.GetLogsResponse
}
var file_activity_logger_v1_activity_logger_proto_depIdxs = []int32{
	3, // 0: activity_logger.v1.GetLogsResponse.logs:type_name -> activity_logger.v1.ActivityLog
	0, // 1: activity_logger.v1.ActivityLogger.LogEvent:input_type -> activity_logger.v1.LogRequest
	2, // 2: activity_logger.v1.ActivityLogger.GetLogs:input_type -> activity_logger.v1.GetLogsRequest
	1, // 3: activity_logger.v1.ActivityLogger.LogEvent:output_type -> activity_logger.v1.LogResponse
	4, // 4: activity_logger.v1.ActivityLogger.GetLogs:output_type -> activity_logger.v1.GetLogsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_activity_logger_v1_activity_logger_proto_init() }
func file_activity_logger_v1_activity_logger_proto_init() {
	if File_activity_logger_v1_activity_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_logger_v1_activity_logger_proto_rawDesc), len(file_activity_logger_v1_activity_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_logger_v1_activity_logger_proto_goTypes,
		DependencyIndexes: file_activity_logger_v1_activity_logger_proto_depIdxs,
		MessageInfos:      file_activity_logger_v1_activity_logger_proto_msgTypes,
	}.Build()
	File_activity_logger_v1_activity_logger_proto = out.File
	file_activity_logger_v1_activity_logger_proto_goTypes = nil
	file_activity_logger_v1_activity_logger_proto_depIdxs = nil
}
