// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: activity_logger/v1/activity_logger.proto

package activity_logger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityLogger_LogEvent_FullMethodName = "/activity_logger.v1.ActivityLogger/LogEvent"
	ActivityLogger_GetLogs_FullMethodName  = "/activity_logger.v1.ActivityLogger/GetLogs"
)

// ActivityLoggerClient is the client API for ActivityLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityLoggerClient interface {
	LogEvent(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type activityLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityLoggerClient(cc grpc.ClientConnInterface) ActivityLoggerClient {
	return &activityLoggerClient{cc}
}

func (c *activityLoggerClient) LogEvent(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, ActivityLogger_LogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityLoggerClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, ActivityLogger_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityLoggerServer is the server API for ActivityLogger service.
// All implementations must embed UnimplementedActivityLoggerServer
// for forward compatibility.
type ActivityLoggerServer interface {
	LogEvent(context.Context, *LogRequest) (*LogResponse, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	mustEmbedUnimplementedActivityLoggerServer()
}

// UnimplementedActivityLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityLoggerServer struct{}

func (UnimplementedActivityLoggerServer) LogEvent(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedActivityLoggerServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedActivityLoggerServer) mustEmbedUnimplementedActivityLoggerServer() {}
func (UnimplementedActivityLoggerServer) testEmbeddedByValue()                        {}

// UnsafeActivityLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityLoggerServer will
// result in compilation errors.
type UnsafeActivityLoggerServer interface {
	mustEmbedUnimplementedActivityLoggerServer()
}

func RegisterActivityLoggerServer(s grpc.ServiceRegistrar, srv ActivityLoggerServer) {
	// If the following call pancis, it indicates UnimplementedActivityLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityLogger_ServiceDesc, srv)
}

func _ActivityLogger_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLoggerServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityLogger_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLoggerServer).LogEvent(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityLogger_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLoggerServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityLogger_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLoggerServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityLogger_ServiceDesc is the grpc.ServiceDesc for ActivityLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity_logger.v1.ActivityLogger",
	HandlerType: (*ActivityLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogEvent",
			Handler:    _ActivityLogger_LogEvent_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _ActivityLogger_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity_logger/v1/activity_logger.proto",
}
