env: "prod"
client_url: "https://todo.chkpnk.ru"
webhook:
  url: "http://email-notifier:8084"
  secret: ""
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
clients:
  activity_logger:
    address: "activity-logger:50051"
    timeout: "2s"
    retries_count: 3
access_token_ttl: 15m
refresh_token_ttl: 168h