env: "local"

app_url: "http://localhost:3030"

smtp:
  host: "smtp-relay.brevo.com"
  port: 587
  username: ""
  password: ""
  from: ""
  sender_name: "ToDoNotificator"

webhook:
  address: "localhost:8084"
  secret: ""