// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kirill010106/todo-notificator/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// LogsGetter is an autogenerated mock type for the LogsGetter type
type LogsGetter struct {
	mock.Mock
}

// GetLogs provides a mock function with given fields: ctx, userID, limit, offset
func (_m *LogsGetter) GetLogs(ctx context.Context, userID int64, limit int32, offset int32) ([]domain.ActivityLog, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []domain.ActivityLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) ([]domain.ActivityLog, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) []domain.ActivityLog); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActivityLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int32, int32) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogsGetter creates a new instance of LogsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogsGetter {
	mock := &LogsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
